In [55]:
import pandas as pd
ratings = pd.read_csv(
    "./ml-1m/ratings.dat",
    sep="::",
    engine="python",
    names=["userId", "movieId", "rating", "timestamp"]
)
ratings = ratings[["userId", "movieId", "timestamp", "rating"]]
ratings.head()

   userId  movieId  timestamp  rating
0       1     1193  978300760       5
1       1      661  978302109       3
2       1      914  978301968       3
3       1     3408  978300275       4
4       1     2355  978824291       5

Encode before Spliting

In [56]:
from sklearn.preprocessing import LabelEncoder

user_encoder = LabelEncoder()
movie_encoder = LabelEncoder()

ratings["user"] = user_encoder.fit_transform(ratings["userId"])
ratings["movie"] = movie_encoder.fit_transform(ratings["movieId"])
ratings["datetime"] = pd.to_datetime(ratings["timestamp"], unit="s")
ratings["day_of_week"] = ratings["datetime"].dt.dayofweek
ratings["month"] = ratings["datetime"].dt.month
ratings.drop("datetime", axis=1, inplace=True)

In [57]:
ratings.head(5)

   userId  movieId  timestamp  rating  user  movie  day_of_week  month
0       1     1193  978300760       5     0   1104            6     12
1       1      661  978302109       3     0    639            6     12
2       1      914  978301968       3     0    853            6     12
3       1     3408  978300275       4     0   3177            6     12
4       1     2355  978824291       5     0   2162            5      1

Split dataset

In [58]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(ratings, test_size=0.2, random_state= 42)

In [59]:
train.head()

        userId  movieId  timestamp  rating  user  movie  day_of_week  month
416292    2507     3035  974076680       2  2506   2821            0     11
683230    4087     2840  965431652       4  4086   2633            4      8
2434        19      457  978146863       3    18    443            5     12
688533    4118     2804  965804599       4  4117   2599            2      8
472584    2907      805  971838472       4  2906    759            2     10

First use ML models to predict the ratings

In [60]:
features = ["user", "movie", "day_of_week", "month"]

X_train = train[features]
y_train = train["rating"]

X_test = test[features]
y_test = test["rating"]

In [61]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np

lr_model = LinearRegression()

lr_model.fit(X_train, y_train)

lr_preds = lr_model.predict(X_test)

lr_rmse = np.sqrt(mean_squared_error(y_test, lr_preds))

print("Linear Regression RMSE:", lr_rmse)

Linear Regression RMSE: 1.1175751236851297

In [62]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=100,
    max_depth=10,
    n_jobs=-1,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_preds = rf_model.predict(X_test)

rf_rmse = np.sqrt(mean_squared_error(y_test, rf_preds))

print("Random Forest RMSE:", rf_rmse)

Random Forest RMSE: 1.0415206126786196